[package]
name = "day_06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
log = "0.4.0"
regex = "1.10.2"
itertools = "0.12.0"
